# Generated by Django 4.0.5 on 2022-07-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='is_removed',
        ),
    ]
